name: ctown
description: "Ctown an Ecommerce"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.03.06+5
version: 2.0.18+162
#version: 0.0.1+5

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  instasoft:
    path: ./modules/common_library
  cupertino_icons: ^1.0.8

  #INVOICE DOWNLOAD
  permission_handler: ^11.3.1
  pdf: ^3.11.1

  # FIREBASE PACKAGES
  cloud_firestore: ^5.6.1
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0

  #STATE MANAGEMENT
  provider: ^6.1.2

  #UI
  quick_actions: ^1.1.0
  flutter_slidable: ^3.1.2
  another_flushbar: ^1.12.30
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  roundcheckbox: ^2.0.5
  animations: ^2.0.11
  awesome_card: ^1.1.7
  carousel_slider: ^5.0.0
  configurable_expansion_tile_null_safety: ^3.3.2
  country_code_picker: ^3.1.0
  country_pickers: ^3.0.1
  flash: ^3.1.1
  flutter_spinkit: ^5.2.1
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intro_slider: ^4.2.1
  liquid_swipe: ^3.1.0
  percent_indicator: ^4.2.4
  pin_code_fields: ^8.0.1
  rate_my_app: ^2.2.0
  rubber: ^1.1.0
  sticky_headers: ^0.3.0+2
  wave: ^0.2.2
  zoom_widget: ^2.0.1
  visibility_detector: ^0.4.0+2
  restart_app: ^1.3.2
  app_settings: ^5.1.1
  badges: ^3.1.2

  #WEB TOOLS
  flutter_html: ^3.0.0-beta.2
  html_unescape: ^2.0.0
  webview_flutter: ^4.10.0
  flutter_widget_from_html: ^0.15.3
  responsive_builder: ^0.7.1
  custom_pop_up_menu: ^1.2.4
  popover: ^0.3.1
  flutter_easyloading: ^3.0.5
  after_layout: ^1.2.0

  # MAP
  google_maps_flutter: ^2.10.0

  # Storage
  shared_preferences: ^2.3.5

  #CONNECTIVITY
  connectivity_plus: ^6.1.1
  http_auth: ^1.0.4
  url_launcher: ^6.3.1
  firebase_dynamic_links: ^6.1.0
  transformable_list_view: ^0.6.0

  # AUTHENTICATION
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.2

  # PUSH NOTIFICATION
  firebase_messaging: ^15.2.0

   # IMAGES
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1

  # TOOLS
  event_bus: ^2.0.1
  google_fonts: ^6.2.1
  random_string: ^2.3.1
  share_plus: ^10.1.3
  json_annotation: ^4.9.0
  timeago: ^3.7.0
  universal_platform: ^1.1.0
  validated: ^2.0.0
  vector_math: ^2.1.4
  async: ^2.11.0
  easy_debounce: ^2.0.3
  jwt_decoder: ^2.0.1
  adaptive_breakpoints: ^0.1.7
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  dio: ^5.7.0
  geolocator: ^13.0.2
  in_app_update: ^4.2.3
  upgrader: ^11.3.1
  flutter_local_notifications: ^18.0.1
  animated_toggle_switch: ^0.8.1


  flutter_localizations:
    sdk: flutter

  collection: ^1.18.0
  uiblock: ^2.0.3
  scrolls_to_top: ^2.1.1
  waterfall_flow: ^3.1.0
  quiver: ^3.2.2
  smooth_page_indicator: ^1.2.0+3
  super_tooltip: ^2.0.9
  sms_autofill: ^2.4.1
  pull_to_refresh_flutter3: ^2.0.2
  firebase_in_app_messaging: ^0.8.1
  firebase_app_installations: ^0.3.2
  googleapis_auth: ^1.6.0
  barcode_scan2: ^4.3.3
  extended_image: ^9.1.0
  algoliasearch: ^1.28.3
  infinite_scroll_pagination: ^4.1.0
  flutter_inappwebview: ^6.1.5
  intl: ^0.19.0
  app_links: ^6.3.3
  flutter_staggered_grid_view: ^0.7.0
  printing: ^5.13.4
  algolia_helper_flutter: ^0.3.3
  algolia: ^1.1.2
  rive: ^0.13.20
  chewie: ^1.9.0
  flutter_cache_manager: ^3.4.1


dependency_overrides:
  localstorage: ^4.0.1+4
  gtext: ^0.0.3
  http: ^0.13.6
  uuid: ^4.5.1
  new_version_plus: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  mockito: ^5.4.4
  build_runner: ^2.4.13
  json_serializable: ^6.9.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"



flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/html/
    - assets/google_fonts/
    - assets/images/splash.gif


flutter_intl:
  enabled: true
